#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

MODE="${1:-full}"
case "$MODE" in
  full|lite) ;;
  *)
    echo "Usage: ./deploy.sh [full|lite]"
    exit 1
    ;;
esac

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif docker-compose version >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  echo "Docker Compose not found. Please install Docker Desktop or docker-compose."
  exit 1
fi

ENV_FILE="$ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
  OWNER_UID="${SUDO_UID:-$(id -u)}"
  OWNER_GID="${SUDO_GID:-$(id -g)}"
  SECRET_VALUE="P3TERX"
  if command -v openssl >/dev/null 2>&1; then
    SECRET_VALUE="$(openssl rand -hex 16)"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh
TZ=Asia/Shanghai

EMOSUP_UID=${OWNER_UID}
EMOSUP_GID=${OWNER_GID}
OPENLIST_UID=${OWNER_UID}
OPENLIST_GID=${OWNER_GID}
ARIA2_UID=${OWNER_UID}
ARIA2_GID=${OWNER_GID}

EMOSUP_DATA_DIR=./data
EMOSUP_DOWNLOADS_DIR=./downloads
OPENLIST_DATA_DIR=./openlist-data
ARIA2_CONFIG_DIR=./aria2-config

EMOSUP_PORT=8080
OPENLIST_PORT=5244
ARIA2_RPC_PORT=6800
ARIA2_LISTEN_PORT=6888
ARIA2_RPC_SECRET=${SECRET_VALUE}
EOF
  echo "Created .env with defaults."
fi

set -a
source "$ENV_FILE"
set +a

mkdir -p "${EMOSUP_DATA_DIR:-./data}" "${EMOSUP_DOWNLOADS_DIR:-./downloads}"
if [ "$MODE" = "full" ]; then
  mkdir -p "${OPENLIST_DATA_DIR:-./openlist-data}" "${ARIA2_CONFIG_DIR:-./aria2-config}"
fi

ensure_ownership() {
  local path="$1"
  if [ ! -e "$path" ]; then
    return 0
  fi
  local current_uid current_gid
  local target_uid target_gid
  current_uid="$(stat -c "%u" "$path" 2>/dev/null || echo "")"
  current_gid="$(stat -c "%g" "$path" 2>/dev/null || echo "")"
  target_uid="${SUDO_UID:-$(id -u)}"
  target_gid="${SUDO_GID:-$(id -g)}"
  if [ "$current_uid" != "$target_uid" ] || [ "$current_gid" != "$target_gid" ]; then
    if [ "$(id -u)" -eq 0 ]; then
      chown -R "${target_uid}:${target_gid}" "$path"
    elif command -v sudo >/dev/null 2>&1; then
      sudo chown -R "${target_uid}:${target_gid}" "$path"
    else
      echo "Warning: $path is owned by ${current_uid}:${current_gid}. Consider chown to ${target_uid}:${target_gid}."
    fi
  fi
}

ensure_ownership "${EMOSUP_DATA_DIR:-./data}"
ensure_ownership "${EMOSUP_DOWNLOADS_DIR:-./downloads}"
if [ "$MODE" = "full" ]; then
  ensure_ownership "${OPENLIST_DATA_DIR:-./openlist-data}"
  ensure_ownership "${ARIA2_CONFIG_DIR:-./aria2-config}"
fi

CONFIG_FILE="${EMOSUP_DATA_DIR:-./data}/config.json"
if [ ! -f "$CONFIG_FILE" ]; then
  if [ "$MODE" = "full" ]; then
    cat > "$CONFIG_FILE" <<EOF
{
  "server": {
    "host": "0.0.0.0",
    "port": 8080
  },
  "openlist": {
    "base_url": "http://openlist:5244",
    "username": "",
    "password": "",
    "token": ""
  },
  "aria2": {
    "rpc_url": "http://aria2:6800/jsonrpc",
    "secret": "${ARIA2_RPC_SECRET:-P3TERX}",
    "download_dir": "/downloads",
    "poll_interval_seconds": 3,
    "connect_timeout_seconds": 10
  },
  "emos": {
    "base_url": "https://emos.best",
    "token": "",
    "storage": "default"
  },
  "worker": {
    "poll_interval_seconds": 5,
    "upload_chunk_size_mb": 8,
    "save_retry_interval_seconds": 25,
    "save_retry_max_attempts": 8
  }
}
EOF
  else
    if [ -f "$ROOT/backend/data/config.example.json" ]; then
      cp "$ROOT/backend/data/config.example.json" "$CONFIG_FILE"
      if command -v sed >/dev/null 2>&1; then
        sed -i 's/"host": "127.0.0.1"/"host": "0.0.0.0"/' "$CONFIG_FILE" || true
      fi
    fi
  fi
fi

COMPOSE_FILE="$ROOT/docker-compose.full.yaml"
if [ "$MODE" = "lite" ]; then
  COMPOSE_FILE="$ROOT/docker-compose.yaml"
fi

"${COMPOSE[@]}" -f "$COMPOSE_FILE" up -d

echo ""
echo "Checking services..."
wait_http() {
  local label="$1"
  local cmd="$2"
  local code="000"
  for _ in $(seq 1 12); do
    code="$(eval "$cmd" || echo 000)"
    if [ "$code" = "200" ] || [ "$code" = "204" ]; then
      break
    fi
    sleep 1
  done
  echo "${label} -> ${code}"
}

wait_http "emosup http://127.0.0.1:${EMOSUP_PORT:-8080}/api/health" \
  "curl -s --max-time 2 -o /dev/null -w \"%{http_code}\" \"http://127.0.0.1:${EMOSUP_PORT:-8080}/api/health\""
if [ "$MODE" = "full" ]; then
  wait_http "openlist http://127.0.0.1:${OPENLIST_PORT:-5244}" \
    "curl -s --max-time 2 -o /dev/null -w \"%{http_code}\" \"http://127.0.0.1:${OPENLIST_PORT:-5244}\""
  wait_http "aria2 http://127.0.0.1:${ARIA2_RPC_PORT:-6800}/jsonrpc" \
    "curl -s --max-time 2 -o /dev/null -w \"%{http_code}\" -X POST \"http://127.0.0.1:${ARIA2_RPC_PORT:-6800}/jsonrpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":\"ping\",\"method\":\"aria2.getVersion\",\"params\":[\"token:${ARIA2_RPC_SECRET:-P3TERX}\"]}'"
fi

echo ""
echo "Done."
