services:
  emosup:
    build:
      context: .
      dockerfile: Dockerfile
    image: emosup:local
    container_name: emosup
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/backend/data
